### ISSUE TITLE
[bug] context menu link scanning

### ISSUE THREAD

**Issue by Dr-Flay** [OPSWAT/metadefender-browser-extension#1]
When using the right-click option with links in pages, if the link uses an image (common with download links) the extension is getting the location of the image instead of the file location.

Browser used: Vivaldi

**Comment by vladoros** [comment]
Hello @Dr-Flay 
Thanks for your suggestion however the context menu option is for scanning images & URLs. For your use case, I suggest downloading the [latest version](https://chrome.google.com/webstore/detail/opswat-file-security-for/fjampemfhdfmangifafmianhokmpjbcj) & enabling safe URL. The URL will be scanned using our IP/URL reputation API.
Also keep an eye out for new features, intercepting file downloads is still work in progress.

**Comment by Dr-Flay** [comment]
Ah I see thanks for clarifying. I assumed it worked like the VT extension.
However I don't see a "Safe URL" option and the extension is updated to v3.6.0.
I see 4 options;
Scan downloads, Share scan results, Show Chrome Notifications, Save clean files.
Should it be there or am I looking in the wrong place ?

**Comment by Dr-Flay** [comment]
I love the new feature and your choice of services !
You include StopForumSpam which I use most days for validating and reporting spammers.
This should make the task a lot easier.
Great idea as they have more info available than the other spam blacklists.
